#version 440

layout(location = 0) in vec2 qt_TexCoord0;
layout(location = 0) out vec4 fragColor;

layout(std140, binding = 0) uniform buf {
    mat4 qt_Matrix;
    float qt_Opacity;

    vec2 size;
    float thickness;
    float rounding;
    float smoothing;
    vec4 borderColor;

    // --- Dedicated Launcher geometry ---
    vec2 launcherPos;
    vec2 launcherSize;
    float launcherRounding;

    // --- Dedicated Clock geometry ---
    vec2 clockPos;
    vec2 clockSize;
    vec4 clockRounding;

    // --- Outer shadow ---
    float shadowEnabledF;
    vec4 shadowColor;
    float shadowOpacity;
    float shadowFalloff;

    // --- Inner edge glow ---
    float innerEdgeEnabledF;
    vec4 innerEdgeColor;
    float innerEdgeIntensity;
    float innerEdgeFalloff;

    // --- Dedicated Launcher Tendril Settings ---
    vec2 launcherTendrilBlend;
    float launcherWaistSmoothing;

    // --- Dedicated Clock Tendril Settings ---
    vec2 clockTendrilBlend;
    float clockWaistSmoothing;

    // ==== Generated by gen_tendril_uniforms.py 64 ====
    vec4 tendril0Pos;
    vec4 tendril1Pos;
    vec4 tendril2Pos;
    vec4 tendril3Pos;
    vec4 tendril4Pos;
    vec4 tendril5Pos;
    vec4 tendril6Pos;
    vec4 tendril7Pos;
    vec4 tendril8Pos;
    vec4 tendril9Pos;
    vec4 tendril10Pos;
    vec4 tendril11Pos;
    vec4 tendril12Pos;
    vec4 tendril13Pos;
    vec4 tendril14Pos;
    vec4 tendril15Pos;
    vec4 tendril16Pos;
    vec4 tendril17Pos;
    vec4 tendril18Pos;
    vec4 tendril19Pos;
    vec4 tendril20Pos;
    vec4 tendril21Pos;
    vec4 tendril22Pos;
    vec4 tendril23Pos;
    vec4 tendril24Pos;
    vec4 tendril25Pos;
    vec4 tendril26Pos;
    vec4 tendril27Pos;
    vec4 tendril28Pos;
    vec4 tendril29Pos;
    vec4 tendril30Pos;
    vec4 tendril31Pos;
    vec4 tendril32Pos;
    vec4 tendril33Pos;
    vec4 tendril34Pos;
    vec4 tendril35Pos;
    vec4 tendril36Pos;
    vec4 tendril37Pos;
    vec4 tendril38Pos;
    vec4 tendril39Pos;
    vec4 tendril40Pos;
    vec4 tendril41Pos;
    vec4 tendril42Pos;
    vec4 tendril43Pos;
    vec4 tendril44Pos;
    vec4 tendril45Pos;
    vec4 tendril46Pos;
    vec4 tendril47Pos;
    vec4 tendril48Pos;
    vec4 tendril49Pos;
    vec4 tendril50Pos;
    vec4 tendril51Pos;
    vec4 tendril52Pos;
    vec4 tendril53Pos;
    vec4 tendril54Pos;
    vec4 tendril55Pos;
    vec4 tendril56Pos;
    vec4 tendril57Pos;
    vec4 tendril58Pos;
    vec4 tendril59Pos;
    vec4 tendril60Pos;
    vec4 tendril61Pos;
    vec4 tendril62Pos;
    vec4 tendril63Pos;

    vec4 tendril0Thick;
    vec4 tendril1Thick;
    vec4 tendril2Thick;
    vec4 tendril3Thick;
    vec4 tendril4Thick;
    vec4 tendril5Thick;
    vec4 tendril6Thick;
    vec4 tendril7Thick;
    vec4 tendril8Thick;
    vec4 tendril9Thick;
    vec4 tendril10Thick;
    vec4 tendril11Thick;
    vec4 tendril12Thick;
    vec4 tendril13Thick;
    vec4 tendril14Thick;
    vec4 tendril15Thick;
    vec4 tendril16Thick;
    vec4 tendril17Thick;
    vec4 tendril18Thick;
    vec4 tendril19Thick;
    vec4 tendril20Thick;
    vec4 tendril21Thick;
    vec4 tendril22Thick;
    vec4 tendril23Thick;
    vec4 tendril24Thick;
    vec4 tendril25Thick;
    vec4 tendril26Thick;
    vec4 tendril27Thick;
    vec4 tendril28Thick;
    vec4 tendril29Thick;
    vec4 tendril30Thick;
    vec4 tendril31Thick;
    vec4 tendril32Thick;
    vec4 tendril33Thick;
    vec4 tendril34Thick;
    vec4 tendril35Thick;
    vec4 tendril36Thick;
    vec4 tendril37Thick;
    vec4 tendril38Thick;
    vec4 tendril39Thick;
    vec4 tendril40Thick;
    vec4 tendril41Thick;
    vec4 tendril42Thick;
    vec4 tendril43Thick;
    vec4 tendril44Thick;
    vec4 tendril45Thick;
    vec4 tendril46Thick;
    vec4 tendril47Thick;
    vec4 tendril48Thick;
    vec4 tendril49Thick;
    vec4 tendril50Thick;
    vec4 tendril51Thick;
    vec4 tendril52Thick;
    vec4 tendril53Thick;
    vec4 tendril54Thick;
    vec4 tendril55Thick;
    vec4 tendril56Thick;
    vec4 tendril57Thick;
    vec4 tendril58Thick;
    vec4 tendril59Thick;
    vec4 tendril60Thick;
    vec4 tendril61Thick;
    vec4 tendril62Thick;
    vec4 tendril63Thick;
    // ==== end generated ====
};

float sdRoundBox(vec2 p, vec2 b, float r) {
    vec2 q = abs(p) - b + r;
    return min(max(q.x, q.y), 0.0) + length(max(q, 0.0)) - r;
}

// Per-corner rounded box: r.x = TL, r.y = TR, r.z = BR, r.w = BL
float sdRoundBox4(vec2 p, vec2 b, vec4 r) {
    float maxR = min(b.x, b.y);
    r = clamp(r, 0.0, maxR);

    r.xy = (p.x > 0.0) ? r.yz : r.xw;
    float rad = (p.y > 0.0) ? r.y : r.x;

    vec2 q = abs(p) - b + rad;
    return min(max(q.x, q.y), 0.0) + length(max(q, 0.0)) - rad;
}

float smin(float a, float b, float k) {
    float h = max(k - abs(a - b), 0.0) / k;
    return min(a, b) - h * h * k * 0.25;
}

float tendrilRadiusProfile(float t, float rootR, float waistR, float panelR, float hw) {
    float linear1 = mix(rootR, waistR, clamp(t / 0.5, 0.0, 1.0));
    float linear2 = mix(waistR, panelR, clamp((t - 0.5) / 0.5, 0.0, 1.0));

    if (hw <= 1e-5) {
        return t < 0.5 ? linear1 : linear2;
    }

    float lo = 0.5 - hw;
    float hi = 0.5 + hw;

    if (t <= lo)
        return linear1;
    if (t >= hi)
        return linear2;

    float edgeLo = mix(rootR, waistR, clamp(lo / 0.5, 0.0, 1.0));
    float edgeHi = mix(waistR, panelR, clamp((hi - 0.5) / 0.5, 0.0, 1.0));
    float localT = smoothstep(0.0, 1.0, (t - lo) / max(hi - lo, 1e-5));
    return mix(edgeLo, edgeHi, localT);
}

float sdTendril(vec2 p, vec2 root, vec2 tip, float rootR, float waistR, float panelR, float waistSmoothingPx) {
    vec2 pa = p - root;
    vec2 ba = tip - root;
    float baLen2 = max(dot(ba, ba), 1e-4);
    float baLen = sqrt(baLen2);
    float t = clamp(dot(pa, ba) / baLen2, 0.0, 1.0);

    float hw = clamp(waistSmoothingPx / max(baLen, 1e-4), 0.0, 0.5);
    float radius = tendrilRadiusProfile(t, rootR, waistR, panelR, hw);

    vec2 closest = root + ba * t;
    return length(p - closest) - radius;
}

float addTendril(float scene, vec2 px, vec4 pos, vec4 thick, vec2 blendK, float waistSmoothing) {
    float act = clamp(thick.w, 0.0, 1.0);
    float rootR = thick.x * act;
    float waistR = thick.y * act;
    float panelR = thick.z * act;

    vec2 root = pos.xy;
    vec2 tip = pos.zw;

    float raw = sdTendril(px, root, tip, rootR, waistR, panelR, waistSmoothing);

    float gate = smoothstep(0.0, 0.02, act);
    float tendrilSDF = mix(1.0e4, raw, gate);

    vec2 ba = tip - root;
    float h = clamp(dot(px - root, ba) / max(dot(ba, ba), 1e-4), 0.0, 1.0);
    float k = mix(blendK.x, blendK.y, h);
    k = max(k * act, 0.001);

    return smin(scene, tendrilSDF, k);
}

// A tendril tip connects to the clock if it's near the clock's bounds:
bool isClockTendril(vec2 tip) {
    vec2 cMin = clockPos - vec2(10.0);
    vec2 cMax = clockPos + clockSize + vec2(10.0);
    return (tip.x >= cMin.x && tip.x <= cMax.x && tip.y >= cMin.y && tip.y <= cMax.y);
}

float addTendrilAuto(float scene, vec2 px, vec4 pos, vec4 thick) {
    bool forClock = isClockTendril(pos.zw);
    vec2 blendK = forClock ? clockTendrilBlend : launcherTendrilBlend;
    float waist = forClock ? clockWaistSmoothing : launcherWaistSmoothing;
    return addTendril(scene, px, pos, thick, blendK, waist);
}

void main() {
    vec2 px = qt_TexCoord0 * size;
    vec2 p = px - size * 0.5;

    // 1. Screen edge frame
    float outerSDF = sdRoundBox(p, size * 0.5, 0.0);
    vec2 innerHalf = size * 0.5 - vec2(thickness);
    float innerSDF = sdRoundBox(p, innerHalf, rounding);
    float ringSDF = max(outerSDF, -innerSDF);

    // 2. Launcher panel SDF
    float launcherSDF = 1.0e4;
    if (launcherSize.x > 1.0 && launcherSize.y > 1.0) {
        vec2 launcherCenter = launcherPos + launcherSize * 0.5;
        launcherSDF = sdRoundBox(px - launcherCenter, launcherSize * 0.5, launcherRounding);
    }

    // 3. Clock panel SDF with per-corner radii
    float clockSDF = 1.0e4;
    if (clockSize.x > 1.0 && clockSize.y > 1.0) {
        vec2 clockCenter = clockPos + clockSize * 0.5;
        clockSDF = sdRoundBox4(px - clockCenter, clockSize * 0.5, clockRounding);
    }

    // 4. Combine both panels into scene
    float panelsSDF = min(launcherSDF, clockSDF);

    float scene = min(ringSDF, panelsSDF);
    float featureSDF = min(-innerSDF, panelsSDF);

    // ==== Generated by gen_tendril_uniforms.py 64 (scene pass) ====
    scene = addTendrilAuto(scene, px, tendril0Pos, tendril0Thick);
    scene = addTendrilAuto(scene, px, tendril1Pos, tendril1Thick);
    scene = addTendrilAuto(scene, px, tendril2Pos, tendril2Thick);
    scene = addTendrilAuto(scene, px, tendril3Pos, tendril3Thick);
    scene = addTendrilAuto(scene, px, tendril4Pos, tendril4Thick);
    scene = addTendrilAuto(scene, px, tendril5Pos, tendril5Thick);
    scene = addTendrilAuto(scene, px, tendril6Pos, tendril6Thick);
    scene = addTendrilAuto(scene, px, tendril7Pos, tendril7Thick);
    scene = addTendrilAuto(scene, px, tendril8Pos, tendril8Thick);
    scene = addTendrilAuto(scene, px, tendril9Pos, tendril9Thick);
    scene = addTendrilAuto(scene, px, tendril10Pos, tendril10Thick);
    scene = addTendrilAuto(scene, px, tendril11Pos, tendril11Thick);
    scene = addTendrilAuto(scene, px, tendril12Pos, tendril12Thick);
    scene = addTendrilAuto(scene, px, tendril13Pos, tendril13Thick);
    scene = addTendrilAuto(scene, px, tendril14Pos, tendril14Thick);
    scene = addTendrilAuto(scene, px, tendril15Pos, tendril15Thick);
    scene = addTendrilAuto(scene, px, tendril16Pos, tendril16Thick);
    scene = addTendrilAuto(scene, px, tendril17Pos, tendril17Thick);
    scene = addTendrilAuto(scene, px, tendril18Pos, tendril18Thick);
    scene = addTendrilAuto(scene, px, tendril19Pos, tendril19Thick);
    scene = addTendrilAuto(scene, px, tendril20Pos, tendril20Thick);
    scene = addTendrilAuto(scene, px, tendril21Pos, tendril21Thick);
    scene = addTendrilAuto(scene, px, tendril22Pos, tendril22Thick);
    scene = addTendrilAuto(scene, px, tendril23Pos, tendril23Thick);
    scene = addTendrilAuto(scene, px, tendril24Pos, tendril24Thick);
    scene = addTendrilAuto(scene, px, tendril25Pos, tendril25Thick);
    scene = addTendrilAuto(scene, px, tendril26Pos, tendril26Thick);
    scene = addTendrilAuto(scene, px, tendril27Pos, tendril27Thick);
    scene = addTendrilAuto(scene, px, tendril28Pos, tendril28Thick);
    scene = addTendrilAuto(scene, px, tendril29Pos, tendril29Thick);
    scene = addTendrilAuto(scene, px, tendril30Pos, tendril30Thick);
    scene = addTendrilAuto(scene, px, tendril31Pos, tendril31Thick);
    scene = addTendrilAuto(scene, px, tendril32Pos, tendril32Thick);
    scene = addTendrilAuto(scene, px, tendril33Pos, tendril33Thick);
    scene = addTendrilAuto(scene, px, tendril34Pos, tendril34Thick);
    scene = addTendrilAuto(scene, px, tendril35Pos, tendril35Thick);
    scene = addTendrilAuto(scene, px, tendril36Pos, tendril36Thick);
    scene = addTendrilAuto(scene, px, tendril37Pos, tendril37Thick);
    scene = addTendrilAuto(scene, px, tendril38Pos, tendril38Thick);
    scene = addTendrilAuto(scene, px, tendril39Pos, tendril39Thick);
    scene = addTendrilAuto(scene, px, tendril40Pos, tendril40Thick);
    scene = addTendrilAuto(scene, px, tendril41Pos, tendril41Thick);
    scene = addTendrilAuto(scene, px, tendril42Pos, tendril42Thick);
    scene = addTendrilAuto(scene, px, tendril43Pos, tendril43Thick);
    scene = addTendrilAuto(scene, px, tendril44Pos, tendril44Thick);
    scene = addTendrilAuto(scene, px, tendril45Pos, tendril45Thick);
    scene = addTendrilAuto(scene, px, tendril46Pos, tendril46Thick);
    scene = addTendrilAuto(scene, px, tendril47Pos, tendril47Thick);
    scene = addTendrilAuto(scene, px, tendril48Pos, tendril48Thick);
    scene = addTendrilAuto(scene, px, tendril49Pos, tendril49Thick);
    scene = addTendrilAuto(scene, px, tendril50Pos, tendril50Thick);
    scene = addTendrilAuto(scene, px, tendril51Pos, tendril51Thick);
    scene = addTendrilAuto(scene, px, tendril52Pos, tendril52Thick);
    scene = addTendrilAuto(scene, px, tendril53Pos, tendril53Thick);
    scene = addTendrilAuto(scene, px, tendril54Pos, tendril54Thick);
    scene = addTendrilAuto(scene, px, tendril55Pos, tendril55Thick);
    scene = addTendrilAuto(scene, px, tendril56Pos, tendril56Thick);
    scene = addTendrilAuto(scene, px, tendril57Pos, tendril57Thick);
    scene = addTendrilAuto(scene, px, tendril58Pos, tendril58Thick);
    scene = addTendrilAuto(scene, px, tendril59Pos, tendril59Thick);
    scene = addTendrilAuto(scene, px, tendril60Pos, tendril60Thick);
    scene = addTendrilAuto(scene, px, tendril61Pos, tendril61Thick);
    scene = addTendrilAuto(scene, px, tendril62Pos, tendril62Thick);
    scene = addTendrilAuto(scene, px, tendril63Pos, tendril63Thick);

    // ==== Generated by gen_tendril_uniforms.py 64 (feature pass) ====
    featureSDF = addTendrilAuto(featureSDF, px, tendril0Pos, tendril0Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril1Pos, tendril1Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril2Pos, tendril2Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril3Pos, tendril3Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril4Pos, tendril4Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril5Pos, tendril5Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril6Pos, tendril6Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril7Pos, tendril7Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril8Pos, tendril8Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril9Pos, tendril9Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril10Pos, tendril10Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril11Pos, tendril11Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril12Pos, tendril12Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril13Pos, tendril13Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril14Pos, tendril14Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril15Pos, tendril15Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril16Pos, tendril16Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril17Pos, tendril17Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril18Pos, tendril18Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril19Pos, tendril19Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril20Pos, tendril20Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril21Pos, tendril21Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril22Pos, tendril22Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril23Pos, tendril23Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril24Pos, tendril24Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril25Pos, tendril25Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril26Pos, tendril26Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril27Pos, tendril27Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril28Pos, tendril28Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril29Pos, tendril29Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril30Pos, tendril30Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril31Pos, tendril31Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril32Pos, tendril32Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril33Pos, tendril33Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril34Pos, tendril34Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril35Pos, tendril35Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril36Pos, tendril36Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril37Pos, tendril37Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril38Pos, tendril38Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril39Pos, tendril39Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril40Pos, tendril40Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril41Pos, tendril41Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril42Pos, tendril42Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril43Pos, tendril43Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril44Pos, tendril44Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril45Pos, tendril45Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril46Pos, tendril46Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril47Pos, tendril47Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril48Pos, tendril48Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril49Pos, tendril49Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril50Pos, tendril50Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril51Pos, tendril51Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril52Pos, tendril52Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril53Pos, tendril53Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril54Pos, tendril54Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril55Pos, tendril55Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril56Pos, tendril56Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril57Pos, tendril57Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril58Pos, tendril58Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril59Pos, tendril59Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril60Pos, tendril60Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril61Pos, tendril61Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril62Pos, tendril62Thick);
    featureSDF = addTendrilAuto(featureSDF, px, tendril63Pos, tendril63Thick);
    // ==== end generated ====

    float coverage = 1.0 - smoothstep(0.0, smoothing, scene);
    float alpha = coverage * borderColor.a * qt_Opacity;

    vec3 fillRGB = borderColor.rgb;
    if (innerEdgeEnabledF > 0.5) {
        float insideDist = max(-featureSDF, 0.0);
        float t = 1.0 - clamp(insideDist / max(innerEdgeFalloff, 0.001), 0.0, 1.0);
        fillRGB = mix(borderColor.rgb, innerEdgeColor.rgb,
                       t * innerEdgeIntensity * innerEdgeColor.a);
    }

    vec3 fillPremul = fillRGB * alpha;
    vec3 outRGB = fillPremul;
    float outA = alpha;

    if (shadowEnabledF > 0.5) {
        float d = max(scene, 0.0);
        float shadowMask = exp(-d / max(shadowFalloff, 0.001)) * shadowOpacity;
        float shadowA = shadowMask * shadowColor.a;

        outRGB = fillPremul + shadowColor.rgb * shadowA * (1.0 - alpha);
        outA = alpha + shadowA * (1.0 - alpha);
    }

    fragColor = vec4(outRGB, outA);
}
