#version 440

layout(location = 0) in vec2 qt_TexCoord0;
layout(location = 0) out vec4 fragColor;

layout(std140, binding = 0) uniform buf {
    mat4 qt_Matrix;
    float qt_Opacity;

    vec2 size;
    float thickness;
    float rounding;
    float smoothing;
    vec4 borderColor;

    // --- Organic inner border ---
    float organicBorderEnabledF;
    float organicBorderAmplitude;
    float organicBorderFrequency;
    float organicBorderAnimationSpeed;
    float organicBorderSeed;
    float organicBorderTime;
    float organicBorderPeakSharpness;
    float organicBorderValleySharpness;
    float organicBorderAnimatedF;
    float organicBorderMorphSpeed;
    float organicBorderAmplitudeRange;

    // --- Dedicated Launcher geometry ---
    vec4 powerRect0;
    vec4 powerRect1;
    vec4 powerRect2;
    vec4 powerRect3;
    vec4 powerRect4;
    vec4 powerSpikes;
    float powerSpikeSharpness;
    float launcherSpikeSharpness;
    float clockSpikeSharpness;
    float traySpikeSharpness;
    float trayMenuSpikeSharpness;
    vec4 launcherSpikes;
    vec4 clockSpikes;
    vec4 traySpikes;
    vec4 trayMenuSpikes;
    vec2 launcherPos;
    vec2 launcherSize;
    float launcherRounding;

    // --- Dedicated Clock geometry ---
    vec2 clockPos;
    vec2 clockSize;
    vec4 clockRounding;

    // --- Dedicated Tray geometry ---
    vec2 trayPos;
    vec2 traySize;
    vec4 trayRounding;
    vec2 trayTendrilBlend;
    float trayWaistSmoothing;

    // --- Dedicated Tray Menu geometry ---
    vec2 trayMenuPos;
    vec2 trayMenuSize;
    vec4 trayMenuRounding;
    vec2 trayMenuTendrilBlend;
    float trayMenuWaistSmoothing;

    // --- Outer shadow ---
    float shadowEnabledF;
    vec4 shadowColor;
    float shadowOpacity;
    float shadowFalloff;

    // --- Inner edge glow ---
    float innerEdgeEnabledF;
    vec4 innerEdgeColor;
    float innerEdgeIntensity;
    float innerEdgeFalloff;

    // --- Dedicated Launcher Tendril Settings ---
    vec2 launcherTendrilBlend;
    float launcherWaistSmoothing;

    // --- Dedicated Clock Tendril Settings ---
    vec2 clockTendrilBlend;
    float clockWaistSmoothing;

    // ==== Generated by gen_tendril_uniforms.py 64 ====
    vec4 tendril0Pos;
    vec4 tendril1Pos;
    vec4 tendril2Pos;
    vec4 tendril3Pos;
    vec4 tendril4Pos;
    vec4 tendril5Pos;
    vec4 tendril6Pos;
    vec4 tendril7Pos;
    vec4 tendril8Pos;
    vec4 tendril9Pos;
    vec4 tendril10Pos;
    vec4 tendril11Pos;
    vec4 tendril12Pos;
    vec4 tendril13Pos;
    vec4 tendril14Pos;
    vec4 tendril15Pos;
    vec4 tendril16Pos;
    vec4 tendril17Pos;
    vec4 tendril18Pos;
    vec4 tendril19Pos;
    vec4 tendril20Pos;
    vec4 tendril21Pos;
    vec4 tendril22Pos;
    vec4 tendril23Pos;
    vec4 tendril24Pos;
    vec4 tendril25Pos;
    vec4 tendril26Pos;
    vec4 tendril27Pos;
    vec4 tendril28Pos;
    vec4 tendril29Pos;
    vec4 tendril30Pos;
    vec4 tendril31Pos;
    vec4 tendril32Pos;
    vec4 tendril33Pos;
    vec4 tendril34Pos;
    vec4 tendril35Pos;
    vec4 tendril36Pos;
    vec4 tendril37Pos;
    vec4 tendril38Pos;
    vec4 tendril39Pos;
    vec4 tendril40Pos;
    vec4 tendril41Pos;
    vec4 tendril42Pos;
    vec4 tendril43Pos;
    vec4 tendril44Pos;
    vec4 tendril45Pos;
    vec4 tendril46Pos;
    vec4 tendril47Pos;
    vec4 tendril48Pos;
    vec4 tendril49Pos;
    vec4 tendril50Pos;
    vec4 tendril51Pos;
    vec4 tendril52Pos;
    vec4 tendril53Pos;
    vec4 tendril54Pos;
    vec4 tendril55Pos;
    vec4 tendril56Pos;
    vec4 tendril57Pos;
    vec4 tendril58Pos;
    vec4 tendril59Pos;
    vec4 tendril60Pos;
    vec4 tendril61Pos;
    vec4 tendril62Pos;
    vec4 tendril63Pos;

    vec4 tendril0Thick;
    vec4 tendril1Thick;
    vec4 tendril2Thick;
    vec4 tendril3Thick;
    vec4 tendril4Thick;
    vec4 tendril5Thick;
    vec4 tendril6Thick;
    vec4 tendril7Thick;
    vec4 tendril8Thick;
    vec4 tendril9Thick;
    vec4 tendril10Thick;
    vec4 tendril11Thick;
    vec4 tendril12Thick;
    vec4 tendril13Thick;
    vec4 tendril14Thick;
    vec4 tendril15Thick;
    vec4 tendril16Thick;
    vec4 tendril17Thick;
    vec4 tendril18Thick;
    vec4 tendril19Thick;
    vec4 tendril20Thick;
    vec4 tendril21Thick;
    vec4 tendril22Thick;
    vec4 tendril23Thick;
    vec4 tendril24Thick;
    vec4 tendril25Thick;
    vec4 tendril26Thick;
    vec4 tendril27Thick;
    vec4 tendril28Thick;
    vec4 tendril29Thick;
    vec4 tendril30Thick;
    vec4 tendril31Thick;
    vec4 tendril32Thick;
    vec4 tendril33Thick;
    vec4 tendril34Thick;
    vec4 tendril35Thick;
    vec4 tendril36Thick;
    vec4 tendril37Thick;
    vec4 tendril38Thick;
    vec4 tendril39Thick;
    vec4 tendril40Thick;
    vec4 tendril41Thick;
    vec4 tendril42Thick;
    vec4 tendril43Thick;
    vec4 tendril44Thick;
    vec4 tendril45Thick;
    vec4 tendril46Thick;
    vec4 tendril47Thick;
    vec4 tendril48Thick;
    vec4 tendril49Thick;
    vec4 tendril50Thick;
    vec4 tendril51Thick;
    vec4 tendril52Thick;
    vec4 tendril53Thick;
    vec4 tendril54Thick;
    vec4 tendril55Thick;
    vec4 tendril56Thick;
    vec4 tendril57Thick;
    vec4 tendril58Thick;
    vec4 tendril59Thick;
    vec4 tendril60Thick;
    vec4 tendril61Thick;
    vec4 tendril62Thick;
    vec4 tendril63Thick;
    vec4 tendril0Profile;
    vec4 tendril1Profile;
    vec4 tendril2Profile;
    vec4 tendril3Profile;
    vec4 tendril4Profile;
    vec4 tendril5Profile;
    vec4 tendril6Profile;
    vec4 tendril7Profile;
    vec4 tendril8Profile;
    vec4 tendril9Profile;
    vec4 tendril10Profile;
    vec4 tendril11Profile;
    vec4 tendril12Profile;
    vec4 tendril13Profile;
    vec4 tendril14Profile;
    vec4 tendril15Profile;
    vec4 tendril16Profile;
    vec4 tendril17Profile;
    vec4 tendril18Profile;
    vec4 tendril19Profile;
    vec4 tendril20Profile;
    vec4 tendril21Profile;
    vec4 tendril22Profile;
    vec4 tendril23Profile;
    vec4 tendril24Profile;
    vec4 tendril25Profile;
    vec4 tendril26Profile;
    vec4 tendril27Profile;
    vec4 tendril28Profile;
    vec4 tendril29Profile;
    vec4 tendril30Profile;
    vec4 tendril31Profile;
    vec4 tendril32Profile;
    vec4 tendril33Profile;
    vec4 tendril34Profile;
    vec4 tendril35Profile;
    vec4 tendril36Profile;
    vec4 tendril37Profile;
    vec4 tendril38Profile;
    vec4 tendril39Profile;
    vec4 tendril40Profile;
    vec4 tendril41Profile;
    vec4 tendril42Profile;
    vec4 tendril43Profile;
    vec4 tendril44Profile;
    vec4 tendril45Profile;
    vec4 tendril46Profile;
    vec4 tendril47Profile;
    vec4 tendril48Profile;
    vec4 tendril49Profile;
    vec4 tendril50Profile;
    vec4 tendril51Profile;
    vec4 tendril52Profile;
    vec4 tendril53Profile;
    vec4 tendril54Profile;
    vec4 tendril55Profile;
    vec4 tendril56Profile;
    vec4 tendril57Profile;
    vec4 tendril58Profile;
    vec4 tendril59Profile;
    vec4 tendril60Profile;
    vec4 tendril61Profile;
    vec4 tendril62Profile;
    vec4 tendril63Profile;
    // ==== end generated ====
};

float sdRoundBox(vec2 p, vec2 b, float r) {
    vec2 q = abs(p) - b + r;
    return min(max(q.x, q.y), 0.0) + length(max(q, 0.0)) - r;
}

float sdRoundBox4(vec2 p, vec2 b, vec4 r) {
    float maxR = min(b.x, b.y);
    r = clamp(r, 0.0, maxR);
    r.xy = (p.x > 0.0) ? r.yz : r.xw;
    float rad = (p.y > 0.0) ? r.y : r.x;
    vec2 q = abs(p) - b + rad;
    return min(max(q.x, q.y), 0.0) + length(max(q, 0.0)) - rad;
}

float smin(float a, float b, float k) {
    float h = max(k - abs(a - b), 0.0) / k;
    return min(a, b) - h * h * k * 0.25;
}

// Project onto a closed chain of four lines and four circular arcs. Each
// candidate carries arc length; adjacent pieces agree at their endpoints.
float spikedPanel(vec2 p, vec2 b, vec4 radii, vec4 profile, float sharpness) {
    vec4 r = clamp(radii, vec4(0.0), vec4(min(b.x, b.y)));
    float d = sdRoundBox4(p, b, r);
    if (profile.x < 0.5 || profile.z <= 0.0 || d > profile.z + 64.0 || d < -64.0) return d;
    float best = 1.0e20;
    float coordinate = 0.0;
    float offset = 0.0;
    for (int i = 0; i < 4; ++i) {
        // Top, right, bottom, left; local frame follows clockwise travel.
        vec2 tangent = i == 0 ? vec2(1,0) : i == 1 ? vec2(0,1) : i == 2 ? vec2(-1,0) : vec2(0,-1);
        vec2 normal = vec2(tangent.y, -tangent.x);
        float halfAlong = (i == 0 || i == 2) ? b.x : b.y;
        float halfAcross = (i == 0 || i == 2) ? b.y : b.x;
        float startR = i == 0 ? r.x : i == 1 ? r.y : i == 2 ? r.z : r.w;
        float endR = i == 0 ? r.y : i == 1 ? r.z : i == 2 ? r.w : r.x;
        vec2 a = tangent * (-halfAlong + startR) + normal * halfAcross;
        float segment = max(0.0, 2.0 * halfAlong - startR - endR);
        float t = clamp(dot(p - a, tangent), 0.0, segment);
        float dist = length(p - a - tangent * t);
        if (dist < best) { best = dist; coordinate = offset + t; }
        offset += segment;
        vec2 center = tangent * (halfAlong - endR) + normal * (halfAcross - endR);
        vec2 delta = p - center;
        float angle = clamp(atan(dot(delta, tangent), dot(delta, normal)), 0.0, 1.57079632679);
        vec2 arcPoint = center + endR * (normal * cos(angle) + tangent * sin(angle));
        dist = length(p - arcPoint);
        if (dist < best) { best = dist; coordinate = offset + endR * angle; }
        offset += endR * 1.57079632679;
    }
    float count = max(1.0, floor(offset * max(profile.y, 0.1) / 100.0 + 0.5));
    float phase = coordinate / max(offset, 1.0) * count;
    float index = mod(floor(phase), count);
    float randomLength = fract(sin(index * 127.1 + 31.7) * 43758.5453);
    float amplitude = profile.z * mix(1.0, randomLength, clamp(profile.w, 0.0, 1.0));
    // Rounded V: nearly linear flanks, smooth roots and tips. Zero slope at
    // cell boundaries keeps unequal neighboring spikes joined smoothly.
    float wave = 0.5 - 0.5 * cos(6.28318530718 * fract(phase));
    float roundedV = (sqrt(wave + 0.04) - 0.2) / (sqrt(1.04) - 0.2);
    // Invert the rounded lobe: concave flanks meet at a pointed tip.
    // At zero retain the original soft lobes; at one the tip is a cusp.
    float pointedV = 1.0 - abs(cos(3.14159265359 * fract(phase)));
    float shape = mix(roundedV, pointedV, clamp(sharpness, 0.0, 1.0));
    return d - amplitude * shape;
}

float tendrilRadiusProfile(float t, float rootR, float waistR, float panelR, float hw) {
    float linear1 = mix(rootR, waistR, clamp(t / 0.5, 0.0, 1.0));
    float linear2 = mix(waistR, panelR, clamp((t - 0.5) / 0.5, 0.0, 1.0));

    if (hw <= 1e-5)
        return t < 0.5 ? linear1 : linear2;

    float lo = 0.5 - hw;
    float hi = 0.5 + hw;

    if (t <= lo)
        return linear1;
    if (t >= hi)
        return linear2;

    float edgeLo = mix(rootR, waistR, clamp(lo / 0.5, 0.0, 1.0));
    float edgeHi = mix(waistR, panelR, clamp((hi - 0.5) / 0.5, 0.0, 1.0));
    float localT = smoothstep(0.0, 1.0, (t - lo) / max(hi - lo, 1e-5));
    return mix(edgeLo, edgeHi, localT);
}

float sdTendril(vec2 p, vec2 root, vec2 tip, float rootR, float waistR, float panelR, float waistSmoothingPx) {
    vec2 pa = p - root;
    vec2 ba = tip - root;
    float baLen2 = max(dot(ba, ba), 1e-4);
    float baLen = sqrt(baLen2);
    float t = clamp(dot(pa, ba) / baLen2, 0.0, 1.0);
    float hw = clamp(waistSmoothingPx / max(baLen, 1e-4), 0.0, 0.5);
    float radius = tendrilRadiusProfile(t, rootR, waistR, panelR, hw);
    vec2 closest = root + ba * t;
    return length(p - closest) - radius;
}

// Return scene and inner-glow distances together: the expensive geometry
// is identical for both passes. Uniform profile comes from the owning manager.
vec2 addTendrilPair(vec2 scene, vec2 px, vec4 pos, vec4 thick, vec4 profile) {
    float act = clamp(thick.w, 0.0, 1.0);
    if (act <= 0.001) return scene;
    vec2 root = pos.xy;
    vec2 tip = pos.zw;
    float maxRadius = max(thick.x, max(thick.y, thick.z)) * act;
    // A conservative enclosing box permits an exact early rejection. A
    // smooth union cannot alter either distance when separated by its radius.
    vec2 q = max(min(root, tip) - vec2(maxRadius) - px,
                 px - max(root, tip) - vec2(maxRadius));
    float lowerBound = length(max(q, vec2(0))) + min(max(q.x, q.y), 0.0);
    float maxBlend = max(max(profile.x, profile.y) * act, 0.001);
    if (min(lowerBound, 1.0e4) >= max(scene.x, scene.y) + maxBlend) return scene;
    float raw = sdTendril(px, root, tip, thick.x * act, thick.y * act, thick.z * act, profile.z);
    float gate = smoothstep(0.0, 0.02, act);
    float distance = mix(1.0e4, raw, gate);
    vec2 ba = tip - root;
    float h = clamp(dot(px - root, ba) / max(dot(ba, ba), 1e-4), 0.0, 1.0);
    float k = max(mix(profile.x, profile.y, h) * act, 0.001);
    return vec2(smin(scene.x, distance, k), smin(scene.y, distance, k));
}

const float PI = 3.14159265358979323846;
const float TAU = 6.28318530717958647692;

float roundedRectPerimeterLength(
    vec2 screenSize,
    float inset,
    float requestedRadius
) {
    float w = max(screenSize.x - 2.0 * inset, 1.0);
    float h = max(screenSize.y - 2.0 * inset, 1.0);
    float r = clamp(requestedRadius, 0.0, min(w, h) * 0.5);

    float straightW = max(w - 2.0 * r, 0.0);
    float straightH = max(h - 2.0 * r, 0.0);
    float quarterArc = PI * 0.5 * r;

    return 2.0 * straightW
         + 2.0 * straightH
         + 4.0 * quarterArc;
}

// Returns a clockwise perimeter distance.
//
// Start: the top point of the top-left rounded corner.
// Direction: top -> top-right arc -> right -> bottom-right arc -> bottom
//            -> bottom-left arc -> left -> top-left arc.
//
// Critically, each straight segment and its neighboring arc use the same
// accumulated distance at their shared endpoint.
float roundedRectPerimeterCoordinate(
    vec2 px,
    vec2 screenSize,
    float inset,
    float requestedRadius
) {
    float x0 = inset;
    float y0 = inset;
    float x1 = screenSize.x - inset;
    float y1 = screenSize.y - inset;

    float w = max(x1 - x0, 1.0);
    float h = max(y1 - y0, 1.0);
    float r = clamp(requestedRadius, 0.0, min(w, h) * 0.5);

    float straightW = max(w - 2.0 * r, 0.0);
    float straightH = max(h - 2.0 * r, 0.0);
    float arc = PI * 0.5 * r;

    // We only need a stable mapping close to the visible rounded boundary.
    // Clamping prevents samples outside the cavity bounds from producing
    // nonsensical accumulated distances.
    vec2 p = clamp(px, vec2(x0, y0), vec2(x1, y1));

    bool left = p.x < x0 + r;
    bool right = p.x > x1 - r;
    bool top = p.y < y0 + r;
    bool bottom = p.y > y1 - r;

    // -------------------------------------------------------------------------
    // Corners first. They must be checked before generic side strips.
    // -------------------------------------------------------------------------

    // Top-left arc:
    // angle -PI/2 at its top endpoint -> s = 0
    // angle -PI at its left endpoint -> s = arc
    if (left && top) {
        vec2 center = vec2(x0 + r, y0 + r);
        vec2 delta = p - center;
        float angle = atan(delta.y, delta.x);
        angle = clamp(angle, -PI, -PI * 0.5);

        float t = (-PI * 0.5 - angle) / (PI * 0.5);
        return arc * t;
    }

    // Top-right arc:
    // angle -PI/2 at top endpoint -> s = arc + straightW
    // angle 0 at right endpoint -> s = arc + straightW + arc
    if (right && top) {
        vec2 center = vec2(x1 - r, y0 + r);
        vec2 delta = p - center;
        float angle = atan(delta.y, delta.x);
        angle = clamp(angle, -PI * 0.5, 0.0);

        float t = (angle + PI * 0.5) / (PI * 0.5);
        return arc + straightW + arc * t;
    }

    // Bottom-right arc:
    // angle 0 at right endpoint -> s = 2*arc + straightW + straightH
    // angle PI/2 at bottom endpoint -> s = 3*arc + straightW + straightH
    if (right && bottom) {
        vec2 center = vec2(x1 - r, y1 - r);
        vec2 delta = p - center;
        float angle = atan(delta.y, delta.x);
        angle = clamp(angle, 0.0, PI * 0.5);

        float t = angle / (PI * 0.5);
        return arc + straightW + arc + straightH + arc * t;
    }

    // Bottom-left arc:
    // angle PI/2 at bottom endpoint -> s = 3*arc + 2*straightW + straightH
    // angle PI at left endpoint -> s = 4*arc + 2*straightW + straightH
    if (left && bottom) {
        vec2 center = vec2(x0 + r, y1 - r);
        vec2 delta = p - center;
        float angle = atan(delta.y, delta.x);

        // atan returns [-PI, PI]. Bottom-left's arc uses [PI/2, PI].
        if (angle < 0.0)
            angle += TAU;

        angle = clamp(angle, PI * 0.5, PI);

        float t = (angle - PI * 0.5) / (PI * 0.5);
        return arc + straightW + arc + straightH + arc + straightW
             + arc * t;
    }

    // -------------------------------------------------------------------------
    // Straight sections after all corners.
    // -------------------------------------------------------------------------

    // Top edge: left to right.
    if (top) {
        return arc + clamp(p.x - (x0 + r), 0.0, straightW);
    }

    // Right edge: top to bottom.
    if (right) {
        return arc + straightW + arc
             + clamp(p.y - (y0 + r), 0.0, straightH);
    }

    // Bottom edge: right to left.
    if (bottom) {
        return arc + straightW + arc + straightH + arc
             + clamp((x1 - r) - p.x, 0.0, straightW);
    }

    // Left edge: bottom to top.
    return arc + straightW + arc + straightH + arc + straightW + arc
         + clamp((y1 - r) - p.y, 0.0, straightH);
}

float harmonicBorderWave(
    float phase,
    float travelTime,
    float seed
) {
    float wave1 = sin(
        phase * 5.0
        + travelTime
        + seed * 0.41
    );

    float wave2 = sin(
        phase * 8.0
        - travelTime * 1.37
        + seed * 1.73
        + 1.90
    );

    float wave3 = sin(
        phase * 13.0
        + travelTime * 0.71
        + seed * 2.31
        + 4.20
    );

    return wave1 * 0.68
         + wave2 * 0.23
         + wave3 * 0.09;
}

float organicBorderDisplacement(vec2 px, vec2 screenSize) {
    if (organicBorderEnabledF < 0.5)
        return 0.0;

    float animateWeight = step(0.5, organicBorderAnimatedF);

    // -------------------------------------------------------------------------
    // Closed rounded-rectangle perimeter coordinate
    // -------------------------------------------------------------------------
    float perimeter = roundedRectPerimeterLength(
        screenSize,
        thickness,
        rounding
    );

    float s = roundedRectPerimeterCoordinate(
        px,
        screenSize,
        thickness,
        rounding
    );

    float safePerimeter = max(perimeter, 1.0);
    float wrappedS = fract(s / safePerimeter) * safePerimeter;

    // -------------------------------------------------------------------------
    // Timing
    //
    // Main travel: uses the configured speed directly, with the existing
    // 0.25 scaling so your working 0–5 UI range remains sensible.
    // -------------------------------------------------------------------------
    float morphTime = organicBorderTime
                    * max(organicBorderMorphSpeed, 0.0)
                    * animateWeight;

    float travelTime = organicBorderTime
                     * max(organicBorderAnimationSpeed, 0.0)
                     * 0.25;

    // Slow variation in travel rate. It cannot reverse movement because its
    // multiplier remains within [0.82, 1.18].
    float speedEnvelope = 1.0 + 0.18 * sin(
        morphTime * 0.41 + organicBorderSeed * 0.83
    );

    travelTime *= speedEnvelope;

    // -------------------------------------------------------------------------
    // Amplitude breathing
    //
    // When animated is false, the amplitude remains exactly at its configured
    // baseline. When true, it changes smoothly, but never goes below 65% of
    // the baseline so the border cannot become flat.
    // -------------------------------------------------------------------------
    float baseAmplitude = max(organicBorderAmplitude, 0.001);

    float amplitudeRange = clamp(
        organicBorderAmplitudeRange,
        0.0,
        baseAmplitude * 0.35
    );

    float amplitudeEnvelope = sin(
        morphTime * 0.57 + organicBorderSeed * 2.11
    );

    float effectiveAmplitude = baseAmplitude;

    if (animateWeight > 0.5) {
        effectiveAmplitude = max(
            baseAmplitude * 0.65,
            baseAmplitude + amplitudeEnvelope * amplitudeRange
        );
    }

    // -------------------------------------------------------------------------
    // Closed harmonic field
    // -------------------------------------------------------------------------
    float normalPhase = wrappedS / safePerimeter * TAU;

    float shape = harmonicBorderWave(
        normalPhase,
        travelTime,
        organicBorderSeed
    );

    // -------------------------------------------------------------------------
    // Top-left loop-seam stabilization
    //
    // `s = 0` and `s = perimeter` describe the exact same physical point.
    // The waveform itself is periodic; this small band smooths over minor
    // numerical/branch differences in the perimeter-coordinate helper.
    // -------------------------------------------------------------------------
    float seamWidth = max(rounding * 0.75, 12.0);
    float seamDistance = min(wrappedS, safePerimeter - wrappedS);

    if (seamDistance < seamWidth) {
        float seamValue = harmonicBorderWave(
            0.0,
            travelTime,
            organicBorderSeed
        );

        float seamT = smoothstep(0.0, seamWidth, seamDistance);
        shape = mix(seamValue, shape, seamT);
    }

    // -------------------------------------------------------------------------
    // Static peak / valley shaping
    // -------------------------------------------------------------------------
    float peakPower = clamp(organicBorderPeakSharpness, 0.80, 1.30);
    float valleyPower = clamp(organicBorderValleySharpness, 0.80, 1.30);

    if (shape >= 0.0)
        shape = pow(shape, peakPower);
    else
        shape = -pow(-shape, valleyPower);

    return shape * effectiveAmplitude;
}

// Returns 0.0 at an active tendril root and transitions smoothly to 1.0
// away from it. The organic cutout displacement is multiplied by this,
// creating a stable, smooth landing zone for each root.
float tendrilRootOrganicMask(vec2 px, vec4 pos, vec4 thick) {
    float activation = clamp(thick.w, 0.0, 1.0);

    // Ignore inactive slots.
    if (activation < 0.001)
        return 1.0;

    vec2 root = pos.xy;

    // This should be wider than the physical root and wider than its smooth
    // union radius, so the wave has enough room to settle before the merge.
    float rootRadius = max(thick.x * activation, 1.0);
    float protectRadius = rootRadius * 3.0 + 18.0;
    float fadeWidth = max(rootRadius * 1.5, 12.0);

    float distanceToRoot = length(px - root);

    return smoothstep(
        protectRadius - fadeWidth,
        protectRadius + fadeWidth,
        distanceToRoot
    );
}

float powerPanelSDF(vec2 px, vec4 rect) {
    if (rect.z <= 1.0 || rect.w <= 1.0) return 1.0e4;
    float radius = min(32.0, min(rect.z, rect.w) * 0.5);
    return spikedPanel(px - rect.xy - rect.zw * 0.5, rect.zw * 0.5,
                      vec4(radius), powerSpikes, powerSpikeSharpness);
}

void main() {
    vec2 px = qt_TexCoord0 * size;
    vec2 p = px - size * 0.5;

    float outerSDF = sdRoundBox(p, size * 0.5, 0.0);
    vec2 innerHalf = size * 0.5 - vec2(thickness);
    float innerSDF = sdRoundBox(p, innerHalf, rounding);

    float rootMask = 1.0;

    if (organicBorderEnabledF > 0.5) {
    // ==== Generated by gen_tendril_uniforms.py 64 (root mask pass) ====
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril0Pos, tendril0Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril1Pos, tendril1Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril2Pos, tendril2Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril3Pos, tendril3Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril4Pos, tendril4Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril5Pos, tendril5Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril6Pos, tendril6Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril7Pos, tendril7Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril8Pos, tendril8Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril9Pos, tendril9Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril10Pos, tendril10Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril11Pos, tendril11Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril12Pos, tendril12Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril13Pos, tendril13Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril14Pos, tendril14Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril15Pos, tendril15Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril16Pos, tendril16Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril17Pos, tendril17Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril18Pos, tendril18Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril19Pos, tendril19Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril20Pos, tendril20Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril21Pos, tendril21Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril22Pos, tendril22Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril23Pos, tendril23Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril24Pos, tendril24Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril25Pos, tendril25Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril26Pos, tendril26Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril27Pos, tendril27Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril28Pos, tendril28Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril29Pos, tendril29Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril30Pos, tendril30Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril31Pos, tendril31Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril32Pos, tendril32Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril33Pos, tendril33Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril34Pos, tendril34Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril35Pos, tendril35Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril36Pos, tendril36Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril37Pos, tendril37Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril38Pos, tendril38Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril39Pos, tendril39Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril40Pos, tendril40Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril41Pos, tendril41Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril42Pos, tendril42Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril43Pos, tendril43Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril44Pos, tendril44Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril45Pos, tendril45Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril46Pos, tendril46Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril47Pos, tendril47Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril48Pos, tendril48Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril49Pos, tendril49Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril50Pos, tendril50Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril51Pos, tendril51Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril52Pos, tendril52Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril53Pos, tendril53Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril54Pos, tendril54Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril55Pos, tendril55Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril56Pos, tendril56Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril57Pos, tendril57Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril58Pos, tendril58Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril59Pos, tendril59Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril60Pos, tendril60Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril61Pos, tendril61Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril62Pos, tendril62Thick));
    rootMask = min(rootMask, tendrilRootOrganicMask(px, tendril63Pos, tendril63Thick));
    }
    // ==== end generated ====

    float organicOffset = organicBorderDisplacement(px, size) * rootMask;
    float organicInnerSDF = innerSDF + organicOffset;
    float ringSDF = max(outerSDF, -organicInnerSDF);

    float launcherSDF = 1.0e4;
    if (launcherSize.x > 1.0 && launcherSize.y > 1.0) {
        vec2 launcherCenter = launcherPos + launcherSize * 0.5;
        launcherSDF = spikedPanel(px - launcherCenter, launcherSize * 0.5, vec4(launcherRounding), launcherSpikes, launcherSpikeSharpness);
    }

    // Clock panel SDF
    float clockSDF = 1.0e4;
    if (clockSize.x > 1.0 && clockSize.y > 1.0) {
        vec2 clockCenter = clockPos + clockSize * 0.5;
        clockSDF = spikedPanel(px - clockCenter, clockSize * 0.5, clockRounding, clockSpikes, clockSpikeSharpness);
    }

    // Tray panel SDF
    float traySDF = 1.0e4;
    if (traySize.x > 1.0 && traySize.y > 1.0) {
        vec2 trayCenter = trayPos + traySize * 0.5;
        traySDF = spikedPanel(px - trayCenter, traySize * 0.5, trayRounding, traySpikes, traySpikeSharpness);
    }

    // Tray menu panel SDF
    float trayMenuSDF = 1.0e4;
    if (trayMenuSize.x > 1.0 && trayMenuSize.y > 1.0) {
        vec2 trayMenuCenter = trayMenuPos + trayMenuSize * 0.5;
        trayMenuSDF = spikedPanel(px - trayMenuCenter, trayMenuSize * 0.5, trayMenuRounding, trayMenuSpikes, trayMenuSpikeSharpness);
    }

    // Combine all panels into scene
    float panelsSDF = min(launcherSDF, min(clockSDF, min(traySDF, trayMenuSDF)));
    panelsSDF = min(panelsSDF, min(min(powerPanelSDF(px, powerRect0), powerPanelSDF(px, powerRect1)),
                                 min(powerPanelSDF(px, powerRect2), powerPanelSDF(px, powerRect3))));
    panelsSDF = min(panelsSDF, powerPanelSDF(px, powerRect4));
    float scene = min(ringSDF, panelsSDF);
    float featureSDF = min(-organicInnerSDF, panelsSDF);

    vec2 distances = vec2(scene, featureSDF);
    // ==== Generated combined tendril pass ====
    distances = addTendrilPair(distances, px, tendril0Pos, tendril0Thick, tendril0Profile);
    distances = addTendrilPair(distances, px, tendril1Pos, tendril1Thick, tendril1Profile);
    distances = addTendrilPair(distances, px, tendril2Pos, tendril2Thick, tendril2Profile);
    distances = addTendrilPair(distances, px, tendril3Pos, tendril3Thick, tendril3Profile);
    distances = addTendrilPair(distances, px, tendril4Pos, tendril4Thick, tendril4Profile);
    distances = addTendrilPair(distances, px, tendril5Pos, tendril5Thick, tendril5Profile);
    distances = addTendrilPair(distances, px, tendril6Pos, tendril6Thick, tendril6Profile);
    distances = addTendrilPair(distances, px, tendril7Pos, tendril7Thick, tendril7Profile);
    distances = addTendrilPair(distances, px, tendril8Pos, tendril8Thick, tendril8Profile);
    distances = addTendrilPair(distances, px, tendril9Pos, tendril9Thick, tendril9Profile);
    distances = addTendrilPair(distances, px, tendril10Pos, tendril10Thick, tendril10Profile);
    distances = addTendrilPair(distances, px, tendril11Pos, tendril11Thick, tendril11Profile);
    distances = addTendrilPair(distances, px, tendril12Pos, tendril12Thick, tendril12Profile);
    distances = addTendrilPair(distances, px, tendril13Pos, tendril13Thick, tendril13Profile);
    distances = addTendrilPair(distances, px, tendril14Pos, tendril14Thick, tendril14Profile);
    distances = addTendrilPair(distances, px, tendril15Pos, tendril15Thick, tendril15Profile);
    distances = addTendrilPair(distances, px, tendril16Pos, tendril16Thick, tendril16Profile);
    distances = addTendrilPair(distances, px, tendril17Pos, tendril17Thick, tendril17Profile);
    distances = addTendrilPair(distances, px, tendril18Pos, tendril18Thick, tendril18Profile);
    distances = addTendrilPair(distances, px, tendril19Pos, tendril19Thick, tendril19Profile);
    distances = addTendrilPair(distances, px, tendril20Pos, tendril20Thick, tendril20Profile);
    distances = addTendrilPair(distances, px, tendril21Pos, tendril21Thick, tendril21Profile);
    distances = addTendrilPair(distances, px, tendril22Pos, tendril22Thick, tendril22Profile);
    distances = addTendrilPair(distances, px, tendril23Pos, tendril23Thick, tendril23Profile);
    distances = addTendrilPair(distances, px, tendril24Pos, tendril24Thick, tendril24Profile);
    distances = addTendrilPair(distances, px, tendril25Pos, tendril25Thick, tendril25Profile);
    distances = addTendrilPair(distances, px, tendril26Pos, tendril26Thick, tendril26Profile);
    distances = addTendrilPair(distances, px, tendril27Pos, tendril27Thick, tendril27Profile);
    distances = addTendrilPair(distances, px, tendril28Pos, tendril28Thick, tendril28Profile);
    distances = addTendrilPair(distances, px, tendril29Pos, tendril29Thick, tendril29Profile);
    distances = addTendrilPair(distances, px, tendril30Pos, tendril30Thick, tendril30Profile);
    distances = addTendrilPair(distances, px, tendril31Pos, tendril31Thick, tendril31Profile);
    distances = addTendrilPair(distances, px, tendril32Pos, tendril32Thick, tendril32Profile);
    distances = addTendrilPair(distances, px, tendril33Pos, tendril33Thick, tendril33Profile);
    distances = addTendrilPair(distances, px, tendril34Pos, tendril34Thick, tendril34Profile);
    distances = addTendrilPair(distances, px, tendril35Pos, tendril35Thick, tendril35Profile);
    distances = addTendrilPair(distances, px, tendril36Pos, tendril36Thick, tendril36Profile);
    distances = addTendrilPair(distances, px, tendril37Pos, tendril37Thick, tendril37Profile);
    distances = addTendrilPair(distances, px, tendril38Pos, tendril38Thick, tendril38Profile);
    distances = addTendrilPair(distances, px, tendril39Pos, tendril39Thick, tendril39Profile);
    distances = addTendrilPair(distances, px, tendril40Pos, tendril40Thick, tendril40Profile);
    distances = addTendrilPair(distances, px, tendril41Pos, tendril41Thick, tendril41Profile);
    distances = addTendrilPair(distances, px, tendril42Pos, tendril42Thick, tendril42Profile);
    distances = addTendrilPair(distances, px, tendril43Pos, tendril43Thick, tendril43Profile);
    distances = addTendrilPair(distances, px, tendril44Pos, tendril44Thick, tendril44Profile);
    distances = addTendrilPair(distances, px, tendril45Pos, tendril45Thick, tendril45Profile);
    distances = addTendrilPair(distances, px, tendril46Pos, tendril46Thick, tendril46Profile);
    distances = addTendrilPair(distances, px, tendril47Pos, tendril47Thick, tendril47Profile);
    distances = addTendrilPair(distances, px, tendril48Pos, tendril48Thick, tendril48Profile);
    distances = addTendrilPair(distances, px, tendril49Pos, tendril49Thick, tendril49Profile);
    distances = addTendrilPair(distances, px, tendril50Pos, tendril50Thick, tendril50Profile);
    distances = addTendrilPair(distances, px, tendril51Pos, tendril51Thick, tendril51Profile);
    distances = addTendrilPair(distances, px, tendril52Pos, tendril52Thick, tendril52Profile);
    distances = addTendrilPair(distances, px, tendril53Pos, tendril53Thick, tendril53Profile);
    distances = addTendrilPair(distances, px, tendril54Pos, tendril54Thick, tendril54Profile);
    distances = addTendrilPair(distances, px, tendril55Pos, tendril55Thick, tendril55Profile);
    distances = addTendrilPair(distances, px, tendril56Pos, tendril56Thick, tendril56Profile);
    distances = addTendrilPair(distances, px, tendril57Pos, tendril57Thick, tendril57Profile);
    distances = addTendrilPair(distances, px, tendril58Pos, tendril58Thick, tendril58Profile);
    distances = addTendrilPair(distances, px, tendril59Pos, tendril59Thick, tendril59Profile);
    distances = addTendrilPair(distances, px, tendril60Pos, tendril60Thick, tendril60Profile);
    distances = addTendrilPair(distances, px, tendril61Pos, tendril61Thick, tendril61Profile);
    distances = addTendrilPair(distances, px, tendril62Pos, tendril62Thick, tendril62Profile);
    distances = addTendrilPair(distances, px, tendril63Pos, tendril63Thick, tendril63Profile);
    scene = distances.x;
    featureSDF = distances.y;

    float coverage = 1.0 - smoothstep(0.0, smoothing, scene);
    float alpha = coverage * borderColor.a * qt_Opacity;

    vec3 fillRGB = borderColor.rgb;
    if (innerEdgeEnabledF > 0.5) {
        float insideDist = max(-featureSDF, 0.0);
        float t = 1.0 - clamp(insideDist / max(innerEdgeFalloff, 0.001), 0.0, 1.0);
        fillRGB = mix(borderColor.rgb, innerEdgeColor.rgb,
                      t * innerEdgeIntensity * innerEdgeColor.a);
    }

    vec3 fillPremul = fillRGB * alpha;
    vec3 outRGB = fillPremul;
    float outA = alpha;

    if (shadowEnabledF > 0.5) {
        float d = max(scene, 0.0);
        float shadowMask = exp(-d / max(shadowFalloff, 0.001)) * shadowOpacity;
        float shadowA = shadowMask * shadowColor.a;
        outRGB = fillPremul + shadowColor.rgb * shadowA * (1.0 - alpha);
        outA = alpha + shadowA * (1.0 - alpha);
    }

    fragColor = vec4(outRGB, outA);
}
